# NLP Exercises

We have five exercises in this section. The exercises are:
1. Build your own tokenizer, where you need to implement two functions to implement a tokenizer based on regular expression.
2. Get tags from Trump speech.
3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.
4. Build your own Bag Of Words implementation using tokenizer created before.
5. Build a 5-gram model and clean up the results.

## Exercise 1. Build your own tokenizer

Build two different tokenizers:
- ``tokenize_sentence``: function tokenizing text into sentences,
- ``tokenize_word``: function tokenizing text into words.

In [21]:
from typing import List
import re

def tokenize_words(text: str) -> list:
    return re.findall(r'\w+', text)

def tokenize_sentence(text: str) -> list:
    sentences = re.split(r'(?<=[.!?])\s*', text)
    return [s.strip() for s in sentences if s.strip()]

text = "Here we go again. I was supposed to add this text later.\
Well, it's 10.p.m. here, and I'm actually having fun making this course. :o\
I hope you are getting along fine with this presentation, I really did try.\
And one last sentence, just so you can test you tokenizers better."

print("Tokenized sentences:")
print(tokenize_sentence(text))

print("Tokenized words:")
print(tokenize_words(text))

Tokenized sentences:
['Here we go again.', 'I was supposed to add this text later.', "Well, it's 10.", 'p.', 'm.', "here, and I'm actually having fun making this course.", ':oI hope you are getting along fine with this presentation, I really did try.', 'And one last sentence, just so you can test you tokenizers better.']
Tokenized words:
['Here', 'we', 'go', 'again', 'I', 'was', 'supposed', 'to', 'add', 'this', 'text', 'later', 'Well', 'it', 's', '10', 'p', 'm', 'here', 'and', 'I', 'm', 'actually', 'having', 'fun', 'making', 'this', 'course', 'oI', 'hope', 'you', 'are', 'getting', 'along', 'fine', 'with', 'this', 'presentation', 'I', 'really', 'did', 'try', 'And', 'one', 'last', 'sentence', 'just', 'so', 'you', 'can', 'test', 'you', 'tokenizers', 'better']


## Exercise 2. Get tags from Trump speech using NLTK

You should use the ``trump.txt`` file, read it and find the tags for each word. Use NLTK for it.

In [14]:
import nltk
nltk.download('punkt_tab')
nltk.download('averaged_perceptron_tagger_eng')
from nltk.tokenize import word_tokenize

file = open("../datasets/trump.txt", "r",encoding="utf-8")
trump = file.read()
words = word_tokenize(trump)

tagged_words = nltk.pos_tag(words)

[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package averaged_perceptron_tagger_eng to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Unzipping taggers\averaged_perceptron_tagger_eng.zip.


In [15]:
tagged_words

[('Thank', 'NNP'),
 ('you', 'PRP'),
 ('very', 'RB'),
 ('much', 'RB'),
 ('.', '.'),
 ('Mr.', 'NNP'),
 ('Speaker', 'NNP'),
 (',', ','),
 ('Mr.', 'NNP'),
 ('Vice', 'NNP'),
 ('President', 'NNP'),
 (',', ','),
 ('Members', 'NNP'),
 ('of', 'IN'),
 ('Congress', 'NNP'),
 (',', ','),
 ('the', 'DT'),
 ('First', 'NNP'),
 ('Lady', 'NNP'),
 ('of', 'IN'),
 ('the', 'DT'),
 ('United', 'NNP'),
 ('States', 'NNPS'),
 (',', ','),
 ('and', 'CC'),
 ('citizens', 'NNS'),
 ('of', 'IN'),
 ('America', 'NNP'),
 (':', ':'),
 ('Tonight', 'NN'),
 (',', ','),
 ('as', 'IN'),
 ('we', 'PRP'),
 ('mark', 'VBP'),
 ('the', 'DT'),
 ('conclusion', 'NN'),
 ('of', 'IN'),
 ('our', 'PRP$'),
 ('celebration', 'NN'),
 ('of', 'IN'),
 ('Black', 'NNP'),
 ('History', 'NNP'),
 ('Month', 'NNP'),
 (',', ','),
 ('we', 'PRP'),
 ('are', 'VBP'),
 ('reminded', 'VBN'),
 ('of', 'IN'),
 ('our', 'PRP$'),
 ('Nation', 'NN'),
 ("'s", 'POS'),
 ('path', 'NN'),
 ('towards', 'NNS'),
 ('civil', 'JJ'),
 ('rights', 'NNS'),
 ('and', 'CC'),
 ('the', 'DT'),
 ('

## Exercise 3. Get the nouns in the last 10 sentences from Trump's speech and find the nouns divided by sentencens. Use SpaCy.

Please use Python list features to get the last 10 sentences and display nouns from it.

In [24]:
import spacy

file = open("../datasets/trump.txt", "r",encoding='utf-8')
trump = file.read() 

nlp = spacy.load("en_core_web_sm")
doc = nlp(trump)

last_10_sentences = list(doc.sents)[-10:]

for i, sentence in enumerate(last_10_sentences, start=1):
    nouns = [token.text
             for token in sentence
             if token.pos_ in ('NOUN', 'PROPN')]
    print(f"{i}. Sentence {sentence.text.strip()}:")
    print(f"Nouns: {nouns}")
    print("---")


1. Sentence When we fulfill this vision, when we celebrate our 250 years of glorious freedom, we will look back on tonight as when this new chapter of American greatness began.:
Nouns: ['vision', 'years', 'freedom', 'tonight', 'chapter', 'greatness']
---
2. Sentence The time for small thinking is over.:
Nouns: ['time', 'thinking']
---
3. Sentence The time for trivial fights is behind us.:
Nouns: ['time', 'fights']
---
4. Sentence We just need the courage to share the dreams that fill our hearts, the bravery to express the hopes that stir our souls, and the confidence to turn those hopes and those dreams into action.:
Nouns: ['courage', 'dreams', 'hearts', 'bravery', 'hopes', 'souls', 'confidence', 'hopes', 'dreams', 'action']
---
5. Sentence From now on, America will be empowered by our aspirations, not burdened by our fears; inspired by the future, not bound by failures of the past; and guided by our vision, not blinded by our doubts.:
Nouns: ['America', 'aspirations', 'fears', 'futur

## Exercise 4. Build your own Bag Of Words implementation using tokenizer created before 

You need to implement following methods:

- ``fit_transform`` - gets a list of strings and returns matrix with it's BoW representation
- ``get_features_names`` - returns list of words corresponding to columns in BoW

In [26]:
import numpy as np


class BagOfWords:
    """Basic BoW implementation."""

    def __init__(self):
        self.__feature_names = []
    
    # your code goes maybe also here    
    
    def fit_transform(self, corpus: list) -> np.array:
        tokenize = [tokenize_words(cor) for cor in corpus]

        unique_words = set()
        for tokens in tokenize:
            unique_words.update(tokens)
        self.__feature_names = sorted(list(unique_words))

        bow_matrix = np.zeros((len(corpus), len(self.__feature_names)), dtype=int)

        word_to_index = {word: i for i, word in enumerate(self.__feature_names)}

        for i, token in enumerate(tokenize):
            for word in token:
                if word in word_to_index:
                    col_index = word_to_index[word]
                    bow_matrix[i, col_index] += 1

        return bow_matrix

    def get_feature_names(self) -> list:
        return self.__feature_names

corpus = [
     'Bag Of Words is based on counting',
     'words occurences throughout multiple documents.',
     'This is the third document.',
     'As you can see most of the words occur only once.',
     'This gives us a pretty sparse matrix, see below. Really, see below',
]    
    
vectorizer = BagOfWords()

X = vectorizer.fit_transform(corpus)
print(X)

vectorizer.get_feature_names()
len(vectorizer.get_feature_names())

[[0 1 1 0 0 1 0 1 0 0 1 0 0 0 1 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 0 1 0 1 0]
 [0 0 0 0 1 0 0 0 0 0 0 1 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 1 1 0 0 0 0]
 [1 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 1 0 1 0 1 0 1 1 0 1 0 1 0 0 0 1 1]
 [0 0 0 1 1 0 1 0 2 0 0 0 0 1 0 1 0 0 0 0 0 0 0 0 1 2 1 0 0 0 1 0 0]]


33

## Exercise 5. Build a 5-gram model and clean up the results.

There are three tasks to do:
1. Use 5-gram model instead of 3.
2. Change to capital letter each first letter of a sentence.
3. Remove the whitespace between the last word in a sentence and . ! or ?.

Hint: for 2. and 3. implement a function called ``clean_generated()`` that takes the generated text and fix both issues at once. It could be easier to fix the text after it's generated rather then doing some changes in the while loop.

In [40]:
nltk.download('gutenberg')
nltk.download('genesis')
nltk.download('inaugural')
nltk.download('nps_chat')
nltk.download('webtext')
nltk.download('treebank')
from nltk.book import *
import random


wall_street = text7.tokens

import re

tokens = wall_street

def cleanup():
    compiled_pattern = re.compile("^[a-zA-Z0-9.!?]")
    clean = list(filter(compiled_pattern.match,tokens))
    return clean
tokens = cleanup()

def build_ngrams():
    ngrams = []
    for i in range(len(tokens)-N+1):
        ngrams.append(tokens[i:i+N])
    return ngrams

def ngram_freqs(ngrams):
    counts = {}

    for ngram in ngrams:
        token_seq  = SEP.join(ngram[:-1])
        last_token = ngram[-1]

        if token_seq not in counts:
            counts[token_seq] = {}

        if last_token not in counts[token_seq]:
            counts[token_seq][last_token] = 0

        counts[token_seq][last_token] += 1

    return counts

def next_word(text, N, counts):

    token_seq = SEP.join(text.split()[-(N-1):])

    if token_seq not in counts:
        token_seq = random.choice(list(counts.keys()))

    choices = counts[token_seq].items()

    total = sum(weight for choice, weight in choices)
    r = random.uniform(0, total)
    upto = 0
    for choice, weight in choices:
        upto += weight;
        if upto > r: return choice
    assert False # should not reach here

[nltk_data] Downloading package gutenberg to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Package gutenberg is already up-to-date!
[nltk_data] Downloading package genesis to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Package genesis is already up-to-date!
[nltk_data] Downloading package inaugural to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Package inaugural is already up-to-date!
[nltk_data] Downloading package nps_chat to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Package nps_chat is already up-to-date!
[nltk_data] Downloading package webtext to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Package webtext is already up-to-date!
[nltk_data] Downloading package treebank to
[nltk_data]     C:\Users\jakub\AppData\Roaming\nltk_data...
[nltk_data]   Package treebank is already up-to-date!


In [45]:
def clean_generated(text: str) -> str:
    text = re.sub(r'\s+([.!?])', r'\1', text)
    text = re.sub(r'(^|[.!?]\s+)([a-z])', lambda m: m.group(1) + m.group(2).upper(), text)
    return text

N=5

SEP=" "

sentence_count=5

ngrams = build_ngrams()
start_seq=None

counts = ngram_freqs(ngrams)

if start_seq is None:
    start_seq = random.choice(list(counts.keys()))

generated = start_seq.lower()

sentences = 0
while sentences < sentence_count:
    generated += SEP + next_word(generated, N, counts)
    sentences += 1 if generated.endswith(('.','!', '?')) else 0

text = clean_generated(generated)
print(text)

14.53 cents up 0.56 cent a pound. The May contract which also is without restraints ended with a gain of 0.54 cent to 14.26 cents. The July delivery rose its daily permissible limit of 0.50 cent a pound to 14.00 cents while other contract months showed near-limit advances. According to reports carried by various news services the Brazilian government told its sugar producers that they wo n't be allowed to have their way says 0 Rep. Edward Markey a Massachusetts Democrat.
